// <auto-generated />
using System;
using Firma_tootajate_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Firma_tootajate_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116224620_addedWorktime")]
    partial class addedWorktime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Firma_tootajate_API.Models.Tootajate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Isikukood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parool")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tunnitasu")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tootajates");
                });

            modelBuilder.Entity("Firma_tootajate_API.Models.Worktime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Kuupaev")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Sissepaas")
                        .HasColumnType("time");

                    b.Property<int>("TootajateId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Valjapaas")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("TootajateId");

                    b.ToTable("Worktimes");
                });

            modelBuilder.Entity("Firma_tootajate_API.Models.Worktime", b =>
                {
                    b.HasOne("Firma_tootajate_API.Models.Tootajate", "Tootajate")
                        .WithMany()
                        .HasForeignKey("TootajateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tootajate");
                });
#pragma warning restore 612, 618
        }
    }
}
